version: "3.4"
services:
 vite_docker:
   image: node:alpine
   container_name: covid19-tracker
   entrypoint: /bin/sh
   ports:
     - 5175:5175
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true